### ISSUE TITLE
Segmentation fault in core

### ISSUE THREAD

**Issue by f-baerenbold** [AquaticEcoDynamics/libaed-water#20]
Hello,

I just updated libaed-water in my Simstrat-AED coupling and now I get a segfault when allocating memory for the external variables. Calling aed_provide_global once works fine, but it fails the second time. More specifically, the error seems to be between lines 453 and 460 in aed_core.F90.

**Comment by casper-boon** [comment]
Thats what you get for including a feature you dont expect anyone to use, I guess.  Should be fixed now.
