### ISSUE TITLE
organic matter model diag setting

### ISSUE THREAD

**Issue by aed-modeller** [AquaticEcoDynamics/libaed-water#41]
https://github.com/AquaticEcoDynamics/libaed-water/blob/19a6b2aad2b67a2a8d8cbc7a8ea4f74e7dba0b9c/src/aed_organic_matter.F90#L323

The diag_level is fixed to 10 when the extra_diag is activated, but options of 0,1,2,3, and 10 are available in the code

**Comment by matthipsey** [comment]
This is the intended operation. Users should input diag_level.
extra_diag is still included just for backward compatibility

diag_level can be read via the namelist
https://github.com/AquaticEcoDynamics/libaed-water/blob/19a6b2aad2b67a2a8d8cbc7a8ea4f74e7dba0b9c/src/aed_organic_matter.F90#L311
