### ISSUE TITLE
issue with atm_din flux

### ISSUE THREAD

**Issue by aed-modeller** [AquaticEcoDynamics/libaed-water#42]
https://github.com/AquaticEcoDynamics/libaed-water/blob/19a6b2aad2b67a2a8d8cbc7a8ea4f74e7dba0b9c/src/aed_nitrogen.F90#L608 

The ATM_DIN flux output doesn't look right. It keeps accmulating with time, but the NO3 and NH4 concentration in the water was not impacted. Possibly same issue with the ATM DIP flux
![0007_A4261165](https://user-images.githubusercontent.com/56393839/153806139-509793f1-5090-4491-9636-37cc95b6e6d4.png)
![nutrient_budget_nitrogen_timeseries](https://user-images.githubusercontent.com/56393839/153806163-d6c03a07-7ac6-4588-8b76-bee1238d203b.png)

**Comment by matthipsey** [comment]
Hi Peisheng
I think this is the same issues, as raised here:
https://github.com/AquaticEcoDynamics/libaed-water/pull/27

I think it is fixed in the latest code, and will work when you use the newer binary.
Matt
